### ISSUE TITLE
output-dir not working

### ISSUE THREAD

**Issue by joshglazer** [hatamiarash7/openapi-generator#4]
I am attempting to use the output-dir setting to generate my code in a folder called `codegen/typescript`, but it does not seem to be working.

Here's how I have configured the step:

```
      - name: Generate code
        uses: hatamiarash7/openapi-generator@v0.2.0
        with:
          generator: typescript-fetch
          openapi-file: docs.yml
          output-dir: ./codegen/typescript
```

I have also tried using `codegen/typescript` without the leading`./` but that did not work either.  In both cases, it appears to be generating the code in a folder using the default naming convention, which is `typescript-fetch-client`.

Is there a different way to use this setting?
